### ISSUE TITLE
Input fields are illegible on a dark KDE theme

### ISSUE THREAD

**Issue by peterhoeg** [davidar/tensor#1]
The "Join room..." and "Say something..." are almost white on white when using a dark KDE theme making it extremely difficult to see what one is writing.
![tensor](https://cloud.githubusercontent.com/assets/722550/11452179/1059d718-961a-11e5-811e-051a5ffd09bb.png)

**Comment by davidar** [comment]
Hmm, odd that it picks up the foreground but not the background colour. Would fixing the text to be black be an ok solution?

**Comment by peterhoeg** [comment]
Sure - as long as it can be read.

I have noticed that HipChat works the same way for what it's worth.
