### ISSUE TITLE
Invalid use of incomplete type ‘class QDebug’

### ISSUE THREAD

**Issue by rbalogic** [davidar/tensor#19]
I got this issue while trying to build tensor in my Ubuntu machine

![selection_029](https://cloud.githubusercontent.com/assets/6650280/24213242/caa55cfc-0f57-11e7-909c-048045e1b5c3.png)

OS - Ubuntu
Version - 16.04

**Comment by KitsuneRal** [comment]
It seems that `ConnectionData` doesn't include `<QDebug>` though it has to - this is actually the libqmatrixclient code, used by Tensor and Quaternion. I wonder which version of Qt you have and which compiler you're building with - I haven't seen this error message before. Anyway, thanks for reporting.

**Comment by KitsuneRal** [comment]
Looking further into your case, I see that `<QDebug>` might actually be not included from the depths of Qt header files in case when `QT_NO_DEBUG_STREAM` is defined. But in that case, I'm afraid, you'll get more unrecoverable errors even if you just throw `#include <QDebug>` into `connectiondata.cpp`.

**Comment by rbalogic** [comment]
@KitsuneRal  My `qmake` version is `2.01a`

**Comment by KitsuneRal** [comment]
@balogic , qmake is a separate tool that has its own versioning. Did you install Qt from PPA or do you use the stock Qt (5.5?) version installed with 16.04?
So far I cannot even reproduce the build problem that you have. It builds fine on my Ubuntu VM.

**Comment by rbalogic** [comment]
@KitsuneRal I haven't installed Qt5 explicitly but I have all the build 
tools needed. Doesn't Ubuntu comes with Qt by default? Does missing 
Qt5 is actually the issue?

**Comment by KitsuneRal** [comment]
To be on the safe side, please do the following:
```sudo apt-get install git cmake qtdeclarative5-dev qtdeclarative5-qtquick2-plugin qtdeclarative5-controls-plugin```
This should install all dependencies you may need.

**Comment by rbalogic** [comment]
@KitsuneRal I've installed it all. But still the same error persists.

**Comment by KitsuneRal** [comment]
I'm out of ideas. Anyway, since in all fairness we actually use `qDebug()` in this file, I'm adding a commit with `#include <QDebug>` to libqmatrixclient now. Can you please do the same (add `#include <QDebug>` to other `#include`s in the file `connectiondata.cpp`), to see that this resolves your problem?

**Comment by rbalogic** [comment]
Now the error changes to `QtCore/QJsonObject` No such file or directory

![selection_030](https://cloud.githubusercontent.com/assets/6650280/24260885/375c3e4c-101b-11e7-926e-637a2fcb2ab8.png)

**Comment by KitsuneRal** [comment]
I just noticed - does it try to compile against Qt 4 instead of Qt 5? Do you actually need Qt 4 on your system?

**Comment by davidar** [comment]
I just got bitten by this, apparently Ubuntu changed the qmake default from qt5 to qt4 at some point... :/

`sudo apt install qt5-default` fixes it

**Comment by ernstki** [comment]
I ran into what appears to be [a very similar problem](https://github.com/ksnip/ksnip-plugin-ocr/issues/4).

I'm not qualified to say if this is what happened _here_, but you'll get this error message if you forget to `#include` the header ([h/t](https://old.reddit.com/r/AskProgramming/comments/bg5mfv/calling_debug_with_incomplete_return_type_qdebug/)).

It's not a very good error message from the compiler, but it sort of makes sense in retrospect, I guess.
