### ISSUE TITLE
PasswordLogin error

### ISSUE THREAD

**Issue by a-andreyev** [davidar/tensor#20]
Connected with #11: I'm receiving "please wait window", but from the console output log I could see this:
```
Job "PasswordLogin" created                                                    
Job "PasswordLogin" status 103 : "Error transferring https://matrix.org/_matrix/client/r0/login - server replied: Forbidden"                                  
Job "PasswordLogin" destroyed
```
with the correct credential.
Version: `f3f3056` (latest master git)

**Comment by KitsuneRal** [comment]
Frankly, this is very puzzling. "Forbidden" means that the request has reached the server but the server rejected it basing on security restrictions. Just a wild guess: are you registered on matrix.org or on some other server?

**Comment by a-andreyev** [comment]
sorry for delay!
looks like it was the issue with the server, because right now I'm able to log in successfully.

homeserver is matrix.org
identity server is vector.im (riot)
