### ISSUE TITLE
Sailfish support

### ISSUE THREAD

**Issue by espritlibre** [davidar/tensor#4]
Hi,
could you provide a link to download a rpm for my jolla and sailfishos ?
Thanks

**Comment by davidar** [comment]
Sorry, the new version of tensor no longer supports sailfish, but this may change in the future.

**Comment by florianjacob** [comment]
@davidar As I coudn't find any information on it, could you explain what the new tensor version is and what has changed, technically?

**Comment by davidar** [comment]
@florianjacob The new version uses [libqmatrixclient](https://github.com/Fxrh/libqmatrixclient) instead of [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk), so it's much faster and less memory-hungry than it was before.

It should be possible to port the new version to Sailfish (and if anyone wishes to do so, please let me know) but I decided to focus on the platforms supported by the official Qt SDK (and QtQuick) for now.

**Comment by florianjacob** [comment]
Thanks alot for the clarification, and :+1: for the move to libqmatrixclient. This seems like a very good idea on the way to improve tensor. :smile:

**Comment by ilpianista** [comment]
@davidar this simple change is needed to build tensor with Qt 5.2 https://github.com/ilpianista/tensor/commit/cc119d46cc39b465bfde2849d01ac86f51b2454f (well, it also need libqmatrixclient with PR #10)

**Comment by ilpianista** [comment]
I built both [Tensor](https://build.merproject.org/package/show/home:ilpianista/tensor) and [Quaternion](https://build.merproject.org/package/show/home:ilpianista/quaternion) for Sailfish, but they requires QtQuick Controls which is not available on Sailfish (Spec files are linked if anyone is interested).

Then I tried to port the QML files to [Silica](https://sailfishos.org/develop/docs/silica/sailfish-silica-all.html/), but this also required some change in the C++ files. Because of this, I'm now starting a new client for Sailfish using the libqmatrixclient library.

**Comment by tchncs** [comment]
Anything new here?
Didn't saw it in your repos, @ilpianista :cry:

**Comment by ilpianista** [comment]
@tchncs I'm still interested and motivated to write one client, but unfortunately I made no progress since then :-(

**Comment by tchncs** [comment]
Thanks for your feedback, these are good and bad news :grin:

**Comment by KitsuneRal** [comment]
@ilpianista, can you indicate which parts you needed in C++? I could probably help without making another client (though, admittedly, chat.qml will have to be replaced entirely).

**Comment by ilpianista** [comment]
@KitsuneRal sure, if we could put some `#ifdef` in the `main.cpp` that would be great!
See [https://github.com/ilpianista/harbour-Base64/blob/master/src/main.cpp#L31](this) as example of the required lines to execute Silica stuff.

**Comment by rbns** [comment]
i just discovered matrix and a native sailfish os client would be a huge advantage over other messengers for me. i'm not really good with c++ and have no real experience with programming apps but i would be willing to help with things where i can :)

**Comment by delijati** [comment]
@ilpianista @davidar im also stuck at the required "QtQuick Controls" problem for my ubunu touch device. I think the best solution is to use a independent QML framework. The only one i could find was https://github.com/papyros/qml-material

**Comment by delijati** [comment]
As it seams [fluid](https://liri.io/blog/2017/01/14/fluid-0.9.0.html) is the new successor

**Comment by delijati** [comment]
or https://github.com/M4rtinK/universal-components

**Comment by rodneyrod** [comment]
Is there any testing I could help out with? I've got a Sailfish OS device that's ready to try out a client in testing.

**Comment by KitsuneRal** [comment]
@rodneyrod Hi again here. As just discussed in the other ticket, let's see where we stand atm with building and starting up Tensor on SailfishOS.

**Comment by rodneyrod** [comment]
Did you want me to test building this in the Sailfish SDK when I get it up and running?

**Comment by KitsuneRal** [comment]
Yes, this is the nearest target here.

**Comment by KitsuneRal** [comment]
The next problem will be to settle on something instead of QtQuick Controls (see the comments above).

**Comment by davidar** [comment]
The easiest solution would probably be to go back to using [Universal Components](https://github.com/M4rtinK/universal-components), as Tensor v0.1 did.

**Comment by cintema** [comment]
Did you eventually build the sailfish-rpm and where can I download it? Since it seems there is no active development going on anyways (according to the repo history), where is the former release rpm?
Thank you.

**Comment by KitsuneRal** [comment]
For the record: the most recent effort to port Tensor to SailfishOS is happening at [Sailbook/harbour-matrix](https://github.com/Sailbook/harbour-matrix).

**Comment by KitsuneRal** [comment]
I suppose this can be closed now that active development for Sailfish has moved to another project (see above).

**Comment by KitsuneRal** [comment]
Just a status report for those interested: FWIW, you might want to take a look at https://openrepos.net/content/sailbook/matriksi - it seems to be a resurrection of @Sailbook's (account deleted now) to port Tensor to SailfishOS (the guy wasn't so much into C++ and struggled with the codebase - admittedly, Qt models are not the simplest thing). Now the client is remade in Python (and QML, of course) without using any of Matrix SDKs; I don't know if it's usable and whether its development continues. So far the repo looks like a one-off block of commits.
