### ISSUE TITLE
SyntaxError: JSON.parse: Parse error

### ISSUE THREAD

**Issue by dakotawhitevalley** [davidar/tensor#5]
When connecting to a custom homeserver over **https**, defining a port number results in
`SyntaxError: JSON.parse: Parse error`

When connecting over **http**, defining a port number results in
`/initialSync error: %s SyntaxError: JSON.parse: Parse error`

Tensor never connects to the server, it shows `Please wait...` and simply hangs.

**Comment by suy** [comment]
This happens for me with current master, just connecting to matrix.org. I can't get logged in. I've traced down the problem, and it seems at qml-request/index.js, on xhr.onreadystate. The response body is empty, and JSON.parse fails.

**Comment by davidar** [comment]
Tensor is now using libqmatrixclient instead of matrix-js-sdk, so this should no longer be a problem. Please open a new issue if you still have problems with the latest version.
